### ISSUE TITLE
Building an iso does not work (mismatched rpm error)

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#404]
This can be reproduced by running the following command:

```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type iso --target-arch arm64 \
    --local \
    quay.io/bootc-extension/httpd:latest
```

Which uses the "quay.io/bootc-extension/httpd:latest" test image which is simply the httpd example from https://gitlab.com/bootc-org/examples 

```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type iso --target-arch arm64 \
    --local \
    quay.io/bootc-extension/httpd:latest
Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signatures
Copying blob sha256:d2d335e3ff36eb2c14653641ee5af2db67eaa148b21142946b4c7f2221bf9bf7
Copying blob sha256:1ff5b3d378b54a54652cc50bee9ff5bac849d28efe63a2f8ab0d0f1853110e57
Copying blob sha256:d1d88850a0e9b4b8d8f3608b8ea75570f678c421aea4235f5da2d980a0c8079a
Copying config sha256:7e40d33bb69963f79d289b9a93822dac304f12c8c557dbb9db901b04fd2e0ab3
Writing manifest to image destination
Generating manifest manifest-iso.json
ERRO[0000] Unable to write container event: write unixgram @f58c0->/run/systemd/journal/socket: sendmsg: no such file or directory
ERRO[0009] Unable to write exec died event: "write unixgram @f58c0->/run/systemd/journal/socket: sendmsg: no such file or directory"
ERRO[0000] Unable to write container event: write unixgram @29261->/run/systemd/journal/socket: sendmsg: no such file or directory
ERRO[0000] Unable to write exec died event: "write unixgram @29261->/run/systemd/journal/socket: sendmsg: no such file or directory"
DONE
Building manifest-iso.json
starting -Pipeline source org.osbuild.containers-storage: 391c942482ae423508b29ec3953f4afaa45a1f1cf1775d323e9eaf6a27fb39ae
Build
  root: <host>
Pipeline source org.osbuild.curl: f19ff56226796b748d2499a94f439cdf794329e7f5cc3fcea5d0f1638ca5f335
Build
  root: <host>
Traceback (most recent call last):
  File "/usr/bin/osbuild", line 33, in <module>
    sys.exit(load_entry_point('osbuild==118', 'console_scripts', 'osbuild')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/osbuild/main_cli.py", line 179, in osbuild_cli
    manifest.download(object_store, monitor, args.libdir)
  File "/usr/lib/python3.12/site-packages/osbuild/pipeline.py", line 418, in download
    source.download(mgr, store, libdir)
  File "/usr/lib/python3.12/site-packages/osbuild/sources.py", line 44, in download
    reply = client.call_with_fds("download", args, fds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/osbuild/host.py", line 384, in call_with_fds
    raise error
osbuild.host.RemoteError: RuntimeError: checksum mismatch: sha256:0053d63a5eb0bc399e2e56a2599a1a09dca20c5bcac36f713a56fec46abac391 https://mirror.cpsc.ucalgary.ca/mirror/centos-stream/9-stream/AppStream/aarch64/os/Packages/perl-Getopt-Long-2.52-4.el9.noarch.rpm
   File "/usr/lib/python3.12/site-packages/osbuild/host.py", line 268, in serve
    reply, reply_fds = self._handle_message(msg, fds)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/osbuild/host.py", line 301, in _handle_message
    ret, fds = self.dispatch(name, args, fds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/osbuild/sources.py", line 123, in dispatch
    self.fetch_all(SourceService.load_items(fds))
  File "/usr/lib/osbuild/sources/org.osbuild.curl", line 142, in fetch_all
    for _ in executor.map(self.fetch_one, *zip(*amended)):
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/osbuild/sources/org.osbuild.curl", line 190, in fetch_one
    raise RuntimeError(f"checksum mismatch: {checksum} {url}")

Error: cannot run osbuild: running osbuild failed: exit status 1
2024/04/29 13:25:13 error: cannot run osbuild: running osbuild failed: exit status 1
```

**Comment by achilleas-k** [comment]
The ISO build inspects the base bootable container to use the rpm repositories to build the ISO from the same content sources that the image itself uses.  It looks like the build selected an out of sync rpm mirror where the file `https://mirror.cpsc.ucalgary.ca/mirror/centos-stream/9-stream/AppStream/aarch64/os/Packages/perl-Getopt-Long-2.52-4.el9.noarch.rpm` is empty and it's failing the checksum validation.

**Comment by cdrage** [comment]
@achilleas-k 

Ah, so from my understanding, is that I have to re-build the image which would pull the correct mirrors, in order to build with bootc-image-builder?

**Comment by achilleas-k** [comment]
> @achilleas-k
> 
> Ah, so from my understanding, is that I have to re-build the image which would pull the correct mirrors, in order to build with bootc-image-builder?

Maybe.  It might select the same mirror during depsolve (through libdnf) or it might not.

**Comment by cdrage** [comment]
> > @achilleas-k
> > Ah, so from my understanding, is that I have to re-build the image which would pull the correct mirrors, in order to build with bootc-image-builder?
> 
> Maybe. It might select the same mirror during depsolve (through libdnf) or it might not.

I've rebuilt the example image using `--no-cache` and it built successfully again, but encountered the same issue unfortunately.

Is there any way to have it check other mirrors for the perl package?

**Comment by achilleas-k** [comment]
> Is there any way to have it check other mirrors for the perl package?

You could modify the base container and set a baseurl for the Appstream repo config to a known good mirror as a workaround.  Not really a long-term solution but should work around the issue for now.

**Comment by ondrejbudai** [comment]
OK, we investigated more, and found out that the mirror denylists `curl` that we use for downloading RPMs. I came up with a workaround: https://github.com/osbuild/osbuild/pull/1765

**Comment by ondrejbudai** [comment]
https://github.com/osbuild/osbuild/pull/1766 is now pulled into the latest bootc-image-builder. It will help with this particular repository problem. :)
