### ISSUE TITLE
Can't build CS10 anaconda-iso

### ISSUE THREAD

**Issue by henrywang** [osbuild/bootc-image-builder#602]
Some packages can't be found in CS10, when build anaconda-iso image.

```
Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signatures
Copying blob sha256:5c3fe7653bc1e6d5b534df2962c6bd218b12400cb717ed24270f074b8a100358
Copying blob sha256:caeb080358bd2b7d19699e6c29e9c648077771530af11fb2ec12edcd1d568b2e
Copying blob sha256:7ea443b6027019b188c84390ea6f8bb2cc2839dc12cb836ed2c98a65df6d82eb
Copying config sha256:0720456cf651f59b3023a8beac096451c41f3da2f6261dce37d3b9494db405d2
Writing manifest to image destination
Generating manifest manifest-anaconda-iso.json
Trying to pull 192.168.100.1:5000/*****:wua1...
Getting image source signatures
Writing manifest to image destination
No match for argument: aajohan-comfortaa-fonts
No match for argument: abattis-cantarell-fonts
No match for argument: bitmap-fangsongti-fonts
No match for argument: khmeros-base-fonts
No match for argument: sil-abyssinica-fonts
No match for argument: tigervnc-server-minimal
No match for argument: tigervnc-server-module
No match for argument: xorg-x11-drivers
No match for argument: xorg-x11-server-Xorg
error install_specs
MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: aajohan-comfortaa-fonts, abattis-cantarell-fonts, bitmap-fangsongti-fonts, khmeros-base-fonts, sil-abyssinica-fonts, tigervnc-server-minimal, tigervnc-server-module, xorg-x11-drivers, xorg-x11-server-Xorg
2024/08/10 03:15:42 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:
DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: aajohan-comfortaa-fonts, abattis-cantarell-fonts, bitmap-fangsongti-fonts, khmeros-base-fonts, sil-abyssinica-fonts, tigervnc-server-minimal, tigervnc-server-module, xorg-x11-drivers, xorg-x11-server-Xorg
```

**Comment by chunfuwen** [comment]
2024-08-15 16:29:41,217 process          L0658 INFO | Running 'sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json  quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=true  --config /config.json  quay.io/centos-bootc/centos-bootc:stream10  --chown 107:107  --rootfs ext4 '
2024-08-15 16:29:41,267 process          L0470 DEBUG| [stderr] time="2024-08-15T16:29:41-04:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
2024-08-15 16:29:49,083 process          L0470 DEBUG| [stdout] Generating manifest manifest-anaconda-iso.json
2024-08-15 16:29:49,203 process          L0470 DEBUG| [stdout] Trying to pull quay.io/centos-bootc/centos-bootc:stream10...
2024-08-15 16:29:52,375 process          L0470 DEBUG| [stdout] Getting image source signatures
2024-08-15 16:30:54,092 process          L0470 DEBUG| [stdout] Writing manifest to image destination
2024-08-15 16:31:04,921 process          L0470 DEBUG| [stdout] No match for argument: aajohan-comfortaa-fonts
2024-08-15 16:31:04,922 process          L0470 DEBUG| [stdout] No match for argument: abattis-cantarell-fonts
2024-08-15 16:31:04,923 process          L0470 DEBUG| [stdout] No match for argument: bitmap-fangsongti-fonts
2024-08-15 16:31:04,928 process          L0470 DEBUG| [stdout] No match for argument: khmeros-base-fonts
2024-08-15 16:31:04,932 process          L0470 DEBUG| [stdout] No match for argument: sil-abyssinica-fonts
2024-08-15 16:31:04,933 process          L0470 DEBUG| [stdout] No match for argument: tigervnc-server-minimal
2024-08-15 16:31:04,934 process          L0470 DEBUG| [stdout] No match for argument: tigervnc-server-module
2024-08-15 16:31:04,935 process          L0470 DEBUG| [stdout] No match for argument: xorg-x11-drivers
2024-08-15 16:31:04,936 process          L0470 DEBUG| [stdout] No match for argument: xorg-x11-server-Xorg
2024-08-15 16:31:04,936 process          L0470 DEBUG| [stdout] error install_specs
2024-08-15 16:31:04,936 process          L0470 DEBUG| [stdout] MarkingErrors: Error occurred when marking packages for installation: Problems in request:
2024-08-15 16:31:04,936 process          L0470 DEBUG| [stdout] missing packages: aajohan-comfortaa-fonts, abattis-cantarell-fonts, bitmap-fangsongti-fonts, khmeros-base-fonts, sil-abyssinica-fonts, tigervnc-server-minimal, tigervnc-server-module, xorg-x11-drivers, xorg-x11-server-Xorg
2024-08-15 16:31:05,015 process          L0470 DEBUG| [stdout] 2024/08/15 20:31:05 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:
2024-08-15 16:31:05,016 process          L0470 DEBUG| [stdout] DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
2024-08-15 16:31:05,016 process          L0470 DEBUG| [stdout] missing packages: aajohan-comfortaa-fonts, abattis-cantarell-fonts, bitmap-fangsongti-fonts, khmeros-base-fonts, sil-abyssinica-fonts, tigervnc-server-minimal, tigervnc-server-module, xorg-x11-drivers, xorg-x11-server-Xorg
2024-08-15 16:31:06,282 process          L0739 INFO | Command 'sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json  quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=true  --config /config.json  quay.io/centos-bootc/centos-bootc:stream10  --chown 107:107  --rootfs ext4 ' finished with 1 after 85.061979333s
2024-08-15 16:31:06,283 stacktrace       L0039 ERROR| 
2024-08-15 16:31:06,283 stacktrace       L0041 ERROR| Reproduced traceback from: /var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/avocado_vt/test.py:292
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR| Traceback (most recent call last):
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py", line 137, in run
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|     raise ex
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py", line 124, in run
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|     prepare_env_and_execute_bib(params, test)
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py", line 99, in prepare_env_and_execute_bib
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|     result = bib_utils.podman_command_build(bib_image_url, disk_image_type, container_url, config_json_file,
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/provider/bootc_image_builder/bootc_image_build_utils.py", line 116, in podman_command_build
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|     ret = process.run(
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado/avocado/utils/process.py", line 1093, in run
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR| avocado.utils.process.CmdError: Command 'sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json  quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=true  --config /config.json  quay.io/centos-bootc/centos-bootc:stream10  --chown 107:107  --rootfs ext4 ' failed.
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR| stdout: b'Generating manifest manifest-anaconda-iso.json\r\nTrying to pull quay.io/centos-bootc/centos-bootc:stream10...\r\nGetting image source signatures\r\nWriting manifest to image destination\r\nNo match for argument: aajohan-comfortaa-fonts\r\nNo match for argument: abattis-cantarell-fonts\r\nNo match for argument: bitmap-fangsongti-fonts\r\nNo match for argument: khmeros-base-fonts\r\nNo match for argument: sil-abyssinica-fonts\r\nNo match for argument: tigervnc-server-minimal\r\nNo match for argument: tigervnc-server-module\r\nNo match for argument: xorg-x11-drivers\r\nNo match for argument: xorg-x11-server-Xorg\r\nerror install_specs\r\nMarkingErrors: Error occurred when marking packages for installation: Problems in request:\r\nmissing packages: aajohan-comfortaa-fonts, abattis-cantarell-fonts, bitmap-fangsongti-fonts, khmeros-base-fonts, sil-abyssinica-fonts, tigervnc-server-minimal, tigervnc-server-module, xorg-x11-drivers, xorg-x11-server-Xorg\r\n2024/08/15 20:31:05 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:\r\nDNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\r\nmissing packages: aajohan-comfortaa-fonts, abattis-cantarell-fonts, bitmap-fangsongti-fonts, khmeros-base-fonts, sil-abyssinica-fonts, tigervnc-server-minimal, tigervnc-server-module, xorg-x11-drivers, xorg-x11-server-Xorg\r\n'
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR| stderr: b'time="2024-08-15T16:29:41-04:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"\n'
2024-08-15 16:31:06,284 stacktrace       L0045 ERROR| additional_info: None
2024-08-15 16:31:06,284 stacktrace       L0046 ERROR|

**Comment by mvo5** [comment]
This should be fixed in git but for some reason there is no release on quay.io since  16 days  (Tue, Jul 30, 2024 11:36 PM) - we are  investigating, I made the aarch64 test there optional for now as it seems to fail to get queue the job but that test was only added recently so there is probably something else going on.

**Comment by shi2wei3** [comment]
Right, recent konflux bib anaconda-iso test is PASS, but I'm not sure why the releaseplan is not triggered.

**Comment by henrywang** [comment]
C10S has the following error:
```
Writing manifest to image destination
Generating manifest manifest-anaconda-iso.json
No match for argument: gdisk
No match for argument: libreport-plugin-bugzilla
No match for argument: libreport-plugin-reportuploader
error install_specs
MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: gdisk, libreport-plugin-bugzilla, libreport-plugin-reportuploader
2024/09/12 08:19:48 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:
DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: gdisk, libreport-plugin-bugzilla, libreport-plugin-reportuploader
```
