### ISSUE TITLE
Cannot use default CS9 image quay.io/centos-bootc/centos-bootc:stream9

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#641]
Looks like the image building process may be broken? Even with the default recommended image.

Unable to build it at all :(

Command used:

```sh
podman \
run \
--rm \
--name \
centos-bootc-bootc-image-builder \
--tty \
--privileged \
--security-opt \
label=type:unconfined_t \
-v \
/Users/cdrage/bootc/foobar:/output/ \
-v \
/var/lib/containers/storage:/var/lib/containers/storage \
--label \
bootc.image.builder=true \
quay.io/centos-bootc/bootc-image-builder:latest-1720185748 \
quay.io/centos-bootc/centos-bootc:stream9 \
--output \
/output/ \
--local \
--type \
raw \
--target-arch \
amd64
```

Output:
```
----------
Generating manifest manifest-raw.json
WARNING: target-arch is experimental and needs an installed 'qemu-user' package
Building manifest-raw.json
starting -Pipeline source org.osbuild.containers-storage: d9ab36685df2182de610e959535eb5cf8526341dd898d3107ea731e3a0cfef7b
Build
  root: <host>
Pipeline build: d0d727c48ed259e30b9df8020508a88d5cfc8bec0e6dc1e71bde148dfb406622
Build
  root: <host>
DONE
  runner: org.osbuild.fedora38 (org.osbuild.fedora38)
org.osbuild.container-deploy: 476ebedbe1329b38e61120a07cd3facc9f70ee3cebb8e63b929ed8bd3783bfe1 {}
time="2024-09-09T19:39:30Z" level=info msg="Image operating system mismatch: image uses OS \"linux\"+architecture \"amd64\"+\"\", expecting one of \"linux+arm64+\\\"v8\\\", linux+arm64+\\\"\\\"\""
Copying blob sha256:9a471e25b71a6f9e92e57ce78cacd15898453ca1935dc8f4c7990a6e2596f8e2
Copying blob sha256:bc1abff2c8d4d62d4e06e3455d87c243f6620d0439dd0ac1c9d2891758c25f75
Copying blob sha256:595ab7b3606f7035488e6ae5d998f00e341fa72241eaea049f1fa34effec02ea
Copying blob sha256:06da22da213f6933494fa5e4f0105fb7cdf2fc5a5103d4ed44aee704068a4aeb
Getting image source signatures
Copying blob sha256:fc23361a01684b634517240504e786926819349172130ca5d7e086e1afdc0c6c
Copying blob sha256:08ee3ddc16f78b39ab27d1b4bf201eec89f498aa63c015099214af69db983cb4
Copying blob sha256:27c7a20a702627a840013c8c779eb5fa1eca9edbcb5551a5723d93ab48a593c0
Copying blob sha256:2615f42eb9487b1f8894db90ed21b4735d4e1b70cadde9ff557cee902092b2cb
Copying blob sha256:cf792b9b489c0c5b47d9601e5d3356af30c833b555eab59eb129beb4cce7a435
Copying blob sha256:0f30028a6081d10dd4082fac5cc0113eed270ea3d3e942d21f19abf114894b4d
Copying blob sha256:b61e212e9d43252b99cf602635546e797b63306992316e1ceaeb1e3b1c682061
Copying blob sha256:89246bd448d9db012398ffa44a7eb9f751a11c23c70d9004b707dda3b73f8ec3
Copying blob sha256:5313f56bce6eb6157c1a67eb31535323893b5ac28ce03e46793aee9c92b8fbb0
Copying blob sha256:8be978066749ec06b7cd84bf6f77e26a19cb6414e6c44a30380fd9b0b775de9a
Copying blob sha256:27ee843a716f8810b641d645d11bfd3a8c85f12b64d9a048b7367c067c54b0a0
Copying blob sha256:7f4854de3164c3df2fa03f8da0039160cda07d6ccf8154fe7a4a1b74d9d2f92b
Copying blob sha256:e0c5bcac01de29b19c2fd50b5fb188c3154334d320a27bbbb563616f9d2e601f
Copying blob sha256:590eeb004f86becac7a5cf755d8ea5ee7e4980690fcca417e564c6b5c42164b6
Copying blob sha256:53ab6275c6bed73af55300dc5189f9bd3d208bcd104f66d95072491f2c012b26
Copying blob sha256:9660186beaf2e589b8a9aae5db03c53275381e4efc5d7426ec29589dc80371e5
Copying blob sha256:25ff64aa046179e20be6eb4781248d0f1bdf474448176434b63917b917910d13
Copying blob sha256:03f8187d462decd660e9d518a136c79c867bae006e6d4ad0e29cd476b7f81f5d
Copying blob sha256:b32c88befd73277e8fee071a70fdbdea2f75afbc5274a81b28fdf93f8734a1be
Copying blob sha256:7fd3632758b032d1f41d535673b314aad8ef42a63eb5eecad56bda93dc344621
Copying blob sha256:c249d73cae1c9cd161a2947f35cd08e9a1c99623263eca77f0c3cf743496d563
Copying blob sha256:5a37bb87e63c323ee6ec1db3c3ef0d380b8c4d56f6ce375a1f6814022172362d
Copying blob sha256:9d24df12e5e38ab6ed1aaa92a247b3d4a7d4d47694d390cee490c3230c052a3e
Copying blob sha256:69b91f1def4779a00343db294a8a0c0a311ee41da671ab64816ef0d87cf7c096
Copying blob sha256:27fc9e7ebcf869565621469a5f6b1f5af1e4491bde33353468cabac0ff141d89
Copying blob sha256:8bf2dcf18ec5748e2c8e10a6120442946787c797e08371844dfafb69955e396d
Copying blob sha256:f24cd4a0d082f0fcec67ffa828116885613fbe6b89b624813edcc756a165091f
Copying blob sha256:382f72544e47237b084319d074ceaf4057d1356b03c8a25cf59c384979fb23f5
Copying blob sha256:820b84cbd588faa72cfadaa25ebe6c5b93e594dafa18ef2ef2a40d86c836d27d
Copying blob sha256:bb6c972328b5b8fae4429e433393179baa6e4825b27cce0caf7586204738c074
Copying blob sha256:7d161c5b31e1473be815535b979222a3c883508e67ad82ac63c08f5e8da5f5b3
Copying blob sha256:de01d566d8c5c65b2b0921f1d2f7db59543e0e931eb7ba807f3a5facf656300b
Copying blob sha256:0b208062497b1bef107c638ec1f838a74953a8e2c8b834982e004eaf178227f7
Copying blob sha256:e7b17c3b3c65e109b5aa89238fcc9748adb6e9b73cf706cdd4bcd1b1b48cabe7
Copying blob sha256:1ada5f77f9577b22c474c680202bdbd75a2c36301c80e203b6b950265a5f07c9
Copying blob sha256:0e7fb01bdc2ec5a3f6602da2c72c771791e25f1f4f03e3a9f350c64e28f6d320
Copying blob sha256:26a3a785f219fe2633158784be312a759dbcdd6e806c6aad38eaae8dacd93b78
Copying blob sha256:a6a662caad1c69be08da3ebbf7ede6b5d79b22bb340b2d37d3aac44620f60755
Copying blob sha256:c3c32fa019eaeb5a21f80af9086289db954715e984ba727aea858a37c3c82675
Copying blob sha256:9935e21791dcfe52e5fdb0e1c2dce6d430dbac5af10d96cb0c92487643886f89
Copying blob sha256:f0f54de7631a7b4876c568954e23358464fb5c06c185c6dfc0698a0f1bad2654
Copying blob sha256:2e2e18f084e4fdeabe29c885db67e43d5bcee18d4e47b16f32fdffde60197219
Copying blob sha256:740338585d840f83aac46361071f33ff70275604f569b9861e7e2f21c4f36ac0
Copying blob sha256:3e8892454a0081d7c4213cc5a9f74e5b793af212aef9b36973596a72d221e32a
Copying blob sha256:2675ca15de27a53ca90e8b3dabb914eb2ec7fd76550865410554664c97368951
Copying blob sha256:e4c1c2d6af8a8c835dded4f7f1c1208ea70f69c9f6033e9b8d55eff2a78bc08d
Copying blob sha256:03c83236cb9c7ea9e1e003716b27306d7d02921d2f5ee6fd10d2105bc0a97469
Copying blob sha256:6b6a86d7a979c1054e3c7e640212c9023a0f13507f6d6cf8c9c0b085899ec176
Copying blob sha256:96c2d68e1d6b437cd48ade0d404dbcb711344584cecc10739ee3d3eab0dbe260
Copying blob sha256:7412e0b3db695aa58c20bfd783cda0d63e21c7e5573baa123811705accb764c8
Copying blob sha256:3a6054cee878ea6e2b403ba9e7285f68571485f5ea77eecc68e37ee08867ebba
Copying blob sha256:47011d2eba8f9a5365a825a1b09aa708407d9f9eba3cb24b30bce9bec3497b96
Copying blob sha256:58e2e3378cd72b8267c9df9ed50f919827ca35020442d3e5518c71f542723552
Copying blob sha256:9cdec38438a583ed2cebbf70c8044b2775f6d9f80c8f61950591c7e8c2ede486
Copying blob sha256:cb1cb8f5987e754ffc9a66dbfcbbb77ebaaf59c1a357998033e41cc119b34e7a
Copying blob sha256:114c94ba7375b8d3205d680d5c72a3d74760b6f2622b7ae16114cfc657fabece
Copying blob sha256:59560120dfd629497921a4b1ef1c778c40c4033f62563fc7eee34db4a7fb2bdd
Copying blob sha256:f0cb8baaa9ee2ea9610f0f1ff99fd285ee83f505b793914677fdff556b90b32f
Copying blob sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1
Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Copying blob sha256:5330e5a020dfbe85e811a92a6a4ea28441d4c8c7e6c0ec7bfa8b94f50993bf3c
Copying blob sha256:7c6b930b03f9fb390fd1ccdd2cbf6249e2dc3a78d07e9a5168c5d7a05cf027e6
Writing manifest to image destination
Copying config sha256:290d0da23f0e25f71c627731790ed2f5df58edff9ff33600bc7832c6f743128c
290d0da23f0e25f71c627731790ed2f5df58edff9ff33600bc7832c6f743128c
Untagged: docker.io/library/tmp-container-deploy-98037018570528:latest
org.osbuild.selinux: d0d727c48ed259e30b9df8020508a88d5cfc8bec0e6dc1e71bde148dfb406622 {
  "exclude_paths": [
    "/sysroot"
  ],
  "labels": {
    "/usr/bin/mount": "system_u:object_r:install_exec_t:s0",

Deleted: 290d0da23f0e25f71c627731790ed2f5df58edff9ff33600bc7832c6f743128c
    "/usr/bin/umount": "system_u:object_r:install_exec_t:s0"
  "file_contexts": "etc/selinux/targeted/contexts/files/file_contexts",
    "/usr/bin/ostree": "system_u:object_r:install_exec_t:s0",
⏱  Duration: 23s
  }
}
setfiles: Regex version mismatch, expected: 10.42 2022-12-11 actual: 10.40 2022-04-14
setfiles: Regex version mismatch, expected: 10.42 2022-12-11 actual: 10.40 2022-04-14

⏱  Duration: 7s
Pipeline ostree-deployment: deed831c24f3bab2786922c1640ac8427d2093e6e85bafc548f0ec6fee282633
Build
  root: d0d727c48ed259e30b9df8020508a88d5cfc8bec0e6dc1e71bde148dfb406622
  runner: org.osbuild.linux (org.osbuild.linux)
org.osbuild.ostree.init-fs: a8aa95a2d93ce7d83d7db5bdb1076d6df182dd87cffeaa035aa64188fe9a3b36 {}
ostree admin init-fs --modern /run/osbuild/tree --sysroot=/run/osbuild/tree

⏱  Duration: 0s
org.osbuild.ostree.os-init: ed19be16250dc5864420c2ff19df932f9a09b25b38cf41e02069a16af1c71b45 {
}
  "osname": "default"
ostree admin os-init default --sysroot=/run/osbuild/tree

org.osbuild.mkdir: 3f000b70b3c336be8df1f2a105137b35c370fa5c3ef7fb8b602f3cc9efe43ebb {
    {
      "mode": 448
    }
      "path": "/boot/efi",
}
  ]
⏱  Duration: 0s
  "paths": [

org.osbuild.ostree.deploy.container: 26c75cd786fe8b330e3a1d167843e2eb565ab5a4f47025076e840b536df002eb {
    "rw",
  "osname": "default",
⏱  Duration: 0s
    "console=tty0",
  "kernel_opts": [
    "console=ttyS0"
  ],
  "rootfs": {
  },
  "mounts": [
    "label": "root"
    "/boot",
  ]
  "target_imgref": "ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream9",
    "/boot/efi"
}
ostree container image deploy --imgref=ostree-unverified-image:containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]290d0da23f0e25f71c627731790ed2f5df58edff9ff33600bc7832c6f743128c --stateroot=default --target-imgref=ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream9 --karg=rw --karg=console=tty0 --karg=console=ttyS0 --karg=root=LABEL=root --sysroot=/run/osbuild/tree
error: Performing deployment: Creating importer: Function not implemented (os error 38)
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 72, in <module>
    r = main(stage_args["tree"],
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 67, in main
    ostree_container_deploy(tree, inputs, osname, target_imgref, kopts)
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 41, in ostree_container_deploy
    ostree.cli("container", "image", "deploy",
  File "/run/osbuild/lib/osbuild/util/ostree.py", line 205, in cli
    return subprocess.run(["ostree"] + args,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,

manifest - failed
⏱  Duration: 0s
Failed
subprocess.CalledProcessError: Command '['ostree', 'container', 'image', 'deploy', '--imgref=ostree-unverified-image:containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]290d0da23f0e25f71c627731790ed2f5df58edff9ff33600bc7832c6f743128c', '--stateroot=default', '--target-imgref=ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream9', '--karg=rw', '--karg=console=tty0', '--karg=console=ttyS0', '--karg=root=LABEL=root', '--sysroot=/run/osbuild/tree']' returned non-zero exit status 1.
2024/09/09 19:40:04 error: cannot run osbuild: running osbuild failed: exit status 1
Container exited with a non-zero exit code.
```

**Comment by cdrage** [comment]
FYI no issues with `quay.io/fedora/fedora-bootc:40` just stream9.

**Comment by cgwalters** [comment]
Dup of https://github.com/osbuild/bootc-image-builder/issues/639

> FYI no issues with quay.io/fedora/fedora-bootc:40 just stream9.

Yeah it's because apparently we never updated to bootc-0.1.15 in f40, will fix
