### ISSUE TITLE
cross build quay.io/centos-bootc/centos-bootc:stream10 arm64 qcow2 failed on x86 Fedora 40 

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#673]
```
on x86 Fedora 40 machine, execute below command to generate arm64 image, but failed



[root@dell-r730-014 images]# sudo podman run     --rm     -it     --privileged     --pull=newer     --security-opt label=type:unconfined_t     -v $(pwd)/output:/output     -v /var/lib/containers/storage:/var/lib/containers/storage     quay.io/centos-bootc/bootc-image-builder:latest     --type qcow2 --target-arch arm64         quay.io/centos-bootc/centos-bootc:stream10
Generating manifest manifest-qcow2.json

....

Copying config bcedb944e9 done   | 
Writing manifest to image destination
DONE
Building manifest-qcow2.json
starting -Pipeline source org.osbuild.containers-storage: 25cfea894655184476ff7ec4d17f100eb4bea9bf3fb2456721dfe544f00d24c9
Build
  root: <host>
Pipeline build: 4946c12ef791785036eace000c1c8af0bffffc45c1ad2b0850f684f37bd4c378
Build
  root: <host>
  runner: org.osbuild.fedora38 (org.osbuild.fedora38)
org.osbuild.container-deploy: 45272718be9c7558f4266fac18359102a986bc0a8fd1b657e7ebcf0593f7e112 {}
time="2024-10-14T07:35:06Z" level=info msg="Image operating system mismatch: image uses OS \"linux\"+architecture \"arm64\"+\"\", expecting one of \"linux+amd64+\\\"\\\"\""
Getting image source signatures
Copying blob sha256:88575d0fc6fbf8313e3e31423d9be8ce471a574487da6903e8b21fecc74ba5c0
Copying blob sha256:d05fdac7ecb21617ff1cd7417ed038e8e45328e935aa9a9b580ed19fe065fe27
Copying blob sha256:3d31391ccb1bf94f59bdbde4903ebd84bf359745b9d9e56b11872b73dfc11260
Copying blob sha256:98376920db325dfca9936ca91998e93c85b345f367dc669724a9b854ff996169
Copying blob sha256:0e196d1b30d7c1093c87cb7694095954b74a3937f1d71701bea9138d08f11228
Copying blob sha256:d5d4e810a6e7ff365e9d7351305326ee2cd21aa529dfc368f0ef23d0c8e3a124
Copying blob sha256:2d1e23163691017e13aa3b5eff475118cf5e66c6173d2b35812164f03535759e
Copying blob sha256:9232e280f73a017f289a96bc6dfbc5d47078792d1415ff7c3a6351781b24e96e
Copying blob sha256:d840cfb16eb19654d6363afc1486fc8fb0e759c92948c17f5d88ddfc14842300
Copying blob sha256:1ab0c9291b457b805f3fd28a7608dfd90fa98d2ed00510892348cd41ca15582c
Copying blob sha256:83e5590c1bbac51ea2a54e1dadb5ca6766e93da9a2c4107c838b4217d8db31a2
Copying blob sha256:3190621cd345c33c3543d56910864fb104a6c494bad2147181d2c4d084a7e7e2
Copying blob sha256:6bf147f79ade4b7987525a9254c516c5387752300be793e8522a67e26b95b9f3
Copying blob sha256:d321603ba5a71572261cdee2dcbf9a0d74f69cb24d52f3c0d2f8c6d1e6e2ee9b
Copying blob sha256:c84817a76bffc3db8090e5215554c7abc18d1a665ac2b5705bc4b53b94620f00
Copying blob sha256:385312c182d8cad335c4ca2079ff609992d585b288c4b961b52705ac5bd867c7
Copying blob sha256:e578baefe6e232096e43902553918708c0cd702c91f48b4a2f1750a61c14fb67
Copying blob sha256:20ae3ef547236afcfe9faefe59c5308d85adff1cebd0dc796a8e7fb07519274d
Copying blob sha256:cd3244bafb051149646e412762714546679d4e9e33993d3cc4b59475cad53e7e
Copying blob sha256:54dd9fd8231ddf3c82f5b1d1fe52566eaa18e5f31f4ba1951e1ac4a16e58153a
Copying blob sha256:716023c12c36816a6fd71fe83f89c17efa1172e54d6d297290bf9a4de78e60f6
Copying blob sha256:35b8859e73fdac38d245a5c15fd7ee9c237540d4d0cc05256ddc53d1a0045ade
Copying blob sha256:9a94cdfe7f5eb3393b9fcf46028ca0d8197a47fe309f32e9670a8f0b29bb2ec5
Copying blob sha256:3bb40459d1175aef008e715072b725b1768d4164c657a5e045c0a7f75bb6d206
Copying blob sha256:e68bb93a8a95867d755f91c06e2db160cadb135f68813d11f28787d4a6ea6f54
Copying blob sha256:20f3506d7c978f20a1ffb59d793530b9af8d0177267212a9a38b4d049249b59d
Copying blob sha256:e9cd6e518966afe97c4c5bb5702ab1b4417ed5e54faeb9bc0dfbc05fd5b6b2c7
Copying blob sha256:2a2089cb7b93d503210958f6f62c61b4e5eff979bdf98de66d484080c0519d75
Copying blob sha256:8a852e59735fe22983b9977861ec68b9d3c09264323bb366ae793395260c20bf
Copying blob sha256:862ac16f0328b8956d3e7e7a9060760901f935b94490fb4cdf267ade869e2924
Copying blob sha256:ab699127aa3154add0bd31b8a49b2a022568d1434f5999d64864d6c00a006489
Copying blob sha256:c6727d11e09afc8a0da37da2f4df4b04bba405fa8fb2167179b03f9ede6f0eca
Copying blob sha256:178e457a598782fc4a7f8bea3bcea600d40c331fb20ad4f5f1a87b1e38f19b7d
Copying blob sha256:d04b399e18eda11671db3e2ca170fd3daa6ddc844f4c4284633956e7aee504b3
Copying blob sha256:bf6d9296c7adb027c123258a0d82e525cdf1b938d1d053cd9375cecb0377e86d
Copying blob sha256:0e0a6479e7970fb2a39a9fcc2411405f571eff554262335904304304ba4dfb51
Copying blob sha256:9c4c9f5c1fc0b4ebef22edad3b146df4825f86e92aff4c20a7d655a823c66cc3
Copying blob sha256:6f3596393c49a147c446dd28636d8e26248ed274519a76c8a8ae12312cbf6cab
Copying blob sha256:1095f83e91f81120f6470647f63f02522081e7ebae651f9f66f353b17d84c390
Copying blob sha256:c308ca4e73c67cd3550ab11c630d3f9d9916c5f6616db2cc9a6b3ae0fe273217
Copying blob sha256:a77c97092938b2958e030698e11f15ad629692065a2eca3ea714cdcf66712a99
Copying blob sha256:6dc2ceb56b25ac0183d82305348316d232976779709a82cc9c6b0814375dcad6
Copying blob sha256:46ecdf4e1d1c493ae47059e9b8af11817679c53d7cc9d5b3684c72ffd4d64aaa
Copying blob sha256:299c0a98ead295341472c97312d233cb43047f3d98c776ed1c874f85d4b1a434
Copying blob sha256:e581bca9f1752a828942548172ac1ae38c488e43a0a8d58acc1555cfe9ed5142
Copying blob sha256:8a69d084174b8c3af6fe5fc661e2de0ac102ce9916fa021754666ba79c036333
Copying blob sha256:efb2a55d95682a78e2836df53b6160db967d6cf3d138e24ac7256dda75c1cd8d
Copying blob sha256:76c564320e5e8c5c31625a98e0def8fa0b3f2e3a24f76e0ed2021caa39a498a3
Copying blob sha256:772f8a3d50c191f39d73912cfd537f546e8bc962a1f797c6a0b4fa0ba23cc263
Copying blob sha256:66ed93c80115ac6e072b4403584f3f845089c8709502e5e1b9846802f7a80cca
Copying blob sha256:2b178f13075b6d3634fac655a8bb5119c1af3128a9846846e3cd5f69508fa193
Copying blob sha256:40f4e197364a26b66c06188f2e2f2e24bb3155b5e0aac29789acc641988ca2d2
Copying blob sha256:70473cf2a5f9231fa1a0cdc63dd2c4687cf24c63852c7e9b55824d3cefe290f9
Copying blob sha256:b494c8223815428c061dfef1f310e5e5977e8cdb834ea3865a5c7d7e1b99e962
Copying blob sha256:1a424b0665cc61b820eac487c3ceff8256b81422f1bb19827b8703323321c977
Copying blob sha256:9a2eeca71f7a5d3b8cbe20332c6f8325a1e626d3df9cd7677bead6ef2bf88718
Copying blob sha256:807134b65d1613e9a4fbe794cc3c39369f4c34d2302a9e4eee4c1dd4f5901151
Copying blob sha256:6ad7b0cf233ceafee2ee0a7613fa2d5d1a487ae8cd435e2c279fcff63e0fea19
Copying blob sha256:81c9c99ab8a7a3f8c688b927a90ea874f52a8a5df516542b32f6fe41de7731cc
Copying blob sha256:a8a091517f9cca4129cbe01c1ab5625da6d6c0bf2383b8b7397d860a081f2acb
Copying blob sha256:45b037a3e4f3c4b1d28f8790ef2f3401c94489d5cd243e1580a5f2777bfb57c6
Copying blob sha256:ece370d47e98f0c795a6cbd10b5580de7285670fb83281a377549fa200175a96
Copying blob sha256:453fb05a3c4180f064f494b3aa24b8d33f8d6c7ac6c3c38192767a581a5f17dd
Copying blob sha256:46f21b000106bc89575d5cc0a1ff3f019136eb07dcc231d8578e446e50ebbfae
Copying blob sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1
Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Copying config sha256:bcedb944e939d7ab74b053c07728f49e8e7daa85284b30aeb9ec30816e4b85e5
Writing manifest to image destination
bcedb944e939d7ab74b053c07728f49e8e7daa85284b30aeb9ec30816e4b85e5
Untagged: docker.io/library/tmp-container-deploy-18607359228450:latest
Deleted: bcedb944e939d7ab74b053c07728f49e8e7daa85284b30aeb9ec30816e4b85e5

⏱  Duration: 36s
org.osbuild.selinux: 4946c12ef791785036eace000c1c8af0bffffc45c1ad2b0850f684f37bd4c378 {
  "file_contexts": "etc/selinux/targeted/contexts/files/file_contexts",
  "exclude_paths": [
    "/sysroot"
  ],
  "labels": {
    "/usr/bin/mount": "system_u:object_r:install_exec_t:s0",
    "/usr/bin/ostree": "system_u:object_r:install_exec_t:s0",
    "/usr/bin/umount": "system_u:object_r:install_exec_t:s0"
  }
}

⏱  Duration: 14s
Pipeline ostree-deployment: 8ab4ec5efd769f1b463b501fd63de5da007e8c9673dc860873fc66bc60082328
Build
  root: 4946c12ef791785036eace000c1c8af0bffffc45c1ad2b0850f684f37bd4c378
  runner: org.osbuild.linux (org.osbuild.linux)
org.osbuild.ostree.init-fs: a886b565cd0ed1814e53d26c5d0ca25e0d8ecb2ed2150fdf1d8fb1bbb67d16a4 {}
ostree admin init-fs --modern /run/osbuild/tree --sysroot=/run/osbuild/tree

⏱  Duration: 32s
org.osbuild.ostree.os-init: 29699a39135972852fcb373b74cf1f9f37a72bc98464312c0de55a46ac06a892 {
  "osname": "default"
}
ostree admin os-init default --sysroot=/run/osbuild/tree

⏱  Duration: 32s
org.osbuild.mkdir: 421235e608774df4b38bc4027b96ecd675cfab730411b73d5b595864d6ddcd98 {
  "paths": [
    {
      "path": "/boot/efi",
      "mode": 448
    }
  ]
}

⏱  Duration: 30s
org.osbuild.ostree.deploy.container: 0d69ac472589e332e290dec4e9925419b1b6d24dd7e345b6bd4da028ef63574c {
  "osname": "default",
  "kernel_opts": [
    "rw",
    "console=tty0",
    "console=ttyS0"
  ],
  "target_imgref": "ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream10",
  "rootfs": {
    "label": "root"
  },
  "mounts": [
    "/boot",
    "/boot/efi"
  ]
}
ostree container image deploy --imgref=ostree-unverified-image:containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]bcedb944e939d7ab74b053c07728f49e8e7daa85284b30aeb9ec30816e4b85e5 --stateroot=default --target-imgref=ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream10 --karg=rw --karg=console=tty0 --karg=console=ttyS0 --karg=root=LABEL=root --sysroot=/run/osbuild/tree
error: Performing deployment: Creating importer: Function not implemented (os error 38)
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 72, in <module>
    r = main(stage_args["tree"],
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 67, in main
    ostree_container_deploy(tree, inputs, osname, target_imgref, kopts)
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 41, in ostree_container_deploy
    ostree.cli("container", "image", "deploy",
  File "/run/osbuild/lib/osbuild/util/ostree.py", line 205, in cli
    return subprocess.run(["ostree"] + args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ostree', 'container', 'image', 'deploy', '--imgref=ostree-unverified-image:containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]bcedb944e939d7ab74b053c07728f49e8e7daa85284b30aeb9ec30816e4b85e5', '--stateroot=default', '--target-imgref=ostree-unverified-registry:quay.io/centos-bootc/centos-bootc:stream10', '--karg=rw', '--karg=console=tty0', '--karg=console=ttyS0', '--karg=root=LABEL=root', '--sysroot=/run/osbuild/tree']' returned non-zero exit status 1.

⏱  Duration: 33s
manifest - failed
Failed
2024/10/14 07:38:09 error: cannot run osbuild: running osbuild failed: exit status 1

```

**Comment by chunfuwen** [comment]
[manifest-qcow2.json](https://github.com/user-attachments/files/17360623/manifest-qcow2.json)

**Comment by cgwalters** [comment]
Dup of https://github.com/osbuild/bootc-image-builder/issues/639
