### ISSUE TITLE
Bib fail to build out anaconda-iso on s390x machine

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#686]
```
(.libvirt-ci-venv-ci-runtest-dnj12O) [root@s390x-kvm-037 libvirt-ci-latest-venv]# sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json   -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json  quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=false  --config /config.json  quay.io/centos-bootc/centos-bootc:stream9
Generating manifest manifest-anaconda-iso.json
Trying to pull quay.io/centos-bootc/centos-bootc:stream9...
Getting image source signatures
Copying blob 5dbc0587e4ad done   | 
Copying blob 61112fafe33f done   | 


Copying blob 530ae152c713 done   | 
Copying blob 530ae152c713 done   | 
Copying blob 530ae152c713 done   | 
...
Copying config 89d757faa1 done   | 
Writing manifest to image destination
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x235d334]

goroutine 1 [running]:
github.com/osbuild/images/pkg/image.(*AnacondaContainerInstaller).InstantiateManifest(0xc000102540, 0xc0005be260, {0x0, 0x0, 0x0}, {0x3071098, 0xc000730850}, 0xc0004983f0)
	/root/go/pkg/mod/github.com/osbuild/images@v0.93.0/pkg/image/anaconda_container_installer.go:88 +0x254
main.manifestForISO(0xc000708000, 0xc0004983f0)
	/build/bib/cmd/bootc-image-builder/image.go:443 +0xdb2
main.Manifest(0xc000708000)
	/build/bib/cmd/bootc-image-builder/image.go:74 +0x9e
main.makeManifest(0xc000708000, {0x2a384ca, 0x6})
	/build/bib/cmd/bootc-image-builder/main.go:106 +0x36
main.manifestFromCobra(0xc00063a908, {0xc00008ec60, 0x1, 0x6})
	/build/bib/cmd/bootc-image-builder/main.go:313 +0x1244
main.cmdBuild(0xc00063a908, {0xc00008ec60, 0x1, 0x6})
	/build/bib/cmd/bootc-image-builder/main.go:424 +0x822
github.com/spf13/cobra.(*Command).execute(0xc00063a908, {0xc00008eba0, 0x6, 0x6})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xb7a
github.com/spf13/cobra.(*Command).ExecuteC(0xc00063a608)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x564
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.run()
	/build/bib/cmd/bootc-image-builder/main.go:656 +0x4e
main.main()
	/build/bib/cmd/bootc-image-builder/main.go:660 +0x24


```

**Comment by mvo5** [comment]
I opened https://github.com/osbuild/bootc-image-builder/pull/692 - I need to look into how to test this on our side but it might be enough and will certainly fix this crash (there might be more hidding because I didn't test this end-to-end yet, maybe via qemu-user once we have the openat2 backport from https://src.fedoraproject.org/rpms/qemu/pull-request/70
