### ISSUE TITLE
bib failed to build Fedora 42(rawhide) anaconda-iso on 

### ISSUE THREAD

**Issue by henrywang** [osbuild/bootc-image-builder#699]
Issue only exists when build Fedora 42 anaconda-iso. Fedora 40 and 41 do not have this issue.

bib info:

- bib image digest: sha256:fca2d8de0ce8fc06f34925f3ef329f94e31d35982fa9c080bfdfbf8407bf9e3c
- bib image vcs ref: 52468d346295fd2f19449257d8794bf551467b13
- bib build date: 2024-10-30T10:07:01

The old bib `sha256:1f9b84e3ba1df0244056deb05c400cca3c19b878e38742ac5a1064ef2ea67ec7` does not have this issue.

```
+ sudo podman run --rm -it --privileged --pull=newer --tls-verify=false --security-opt label=type:unconfined_t -v /var/ARTIFACTS/work-anaconda-iso9tx7kurh/tmt/plans/bib-image/anaconda-iso/discover/default-0/tests/output:/output -v /var/lib/containers/storage:/var/lib/containers/storage quay.io/centos-bootc/bootc-image-builder:latest --type anaconda-iso --target-arch x86_64 --chown 0:0 --rootfs ext4 --local 192.168.100.1:5000/hidden:6n6i
time="2024-10-31T05:35:18Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signatures
Copying blob sha256:3120506acc4e09f699fe3797eb9208e8a1759cbfef2414e939f5108ee330a903
Copying blob sha256:60f0e370aaf7e0f8007dde1ffd12f4a623d47a5741dd7e0d223f0f6037cc121b
Copying blob sha256:757a1e9851dcc80cc8b91fd88888a1c6e1d83ee4f4962e38ea6d7fbf3cc018d0
Copying config sha256:976167a928e5ec8593ec4cd4063d13fa43860efbe0705c5eff8784523c1496a3
Writing manifest to image destination
Generating manifest manifest-anaconda-iso.json
Traceback (most recent call last):
  File "/osbuild-depsolve-dnf", line 30, in <module>
    from osbuild.solver.dnf import DNF as Solver
  File "/osbuild/solver/dnf.py", line 7, in <module>
    import dnf
ModuleNotFoundError: No module named 'dnf'
2024/10/31 05:35:31 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:
DNF error occurred: InternalError: dnf-json output was empty
```

**Comment by achilleas-k** [comment]
This should be fixed by #704

**Comment by henrywang** [comment]
Yes, issue fixed.
