### ISSUE TITLE
Bib break anaconda-iso build on Fedora 41

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#700]
```
sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json    -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json   quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=true  --config /config.json  quay.io/fedora/fedora-bootc:41  --chown 107:107  --rootfs xfs

Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signaturesr/lib/libvirt/images/
Copying blob 2b054662280c done   | 
Copying blob 27bd6671c90f done   | 
Copying blob d651a781d40e done   | 
Copying config b7befecd2e done   | 
Writing manifest to image destination
Generating manifest manifest-anaconda-iso.json
Trying to pull quay.io/fedora/fedora-bootc:41...
Getting image source signatures
Copying blob 953770343a39 done   | 
Copying blob 953770343a39 done   | 
Copying blob 2a318413e6e2 done   | 
...
Copying blob a855da5d6fbe done   | 
Copying blob 4f0bf6084203 done   | 
Copying blob 9dad063a624b done   | 
Copying config 7562d2b879 done   | 
Writing manifest to image destination
Traceback (most recent call last):
  File "/osbuild-depsolve-dnf", line 30, in <module>
    from osbuild.solver.dnf import DNF as Solver
  File "/osbuild/solver/dnf.py", line 7, in <module>
    import dnf
ModuleNotFoundError: No module named 'dnf'
2024/11/03 01:40:05 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:

```

**Comment by chunfuwen** [comment]
```
[root@xx-mages]# skopeo inspect docker://quay.io/fedora/fedora-bootc:41 | jq  -r '.Labels' |tee label.log
{
  "containers.bootc": "1",
  "org.opencontainers.image.version": "41.20241101.0",
  "ostree.bootable": "true",
  "ostree.commit": "dd4dc5440e420dbfd79c4581b62f50ad2078cad7c59e751060d8c3a45884712b",
  "ostree.final-diffid": "sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1",
  "ostree.linux": "6.11.5-300.fc41.x86_64",
  "rpmostree.inputhash": "0392ac123f2a091aaa006a5876825839c543a8db6cc11b51a199e4ee16531cd4"
}

```

**Comment by MoralCode** [comment]
I can replicate this on my fedora machine with `sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v ./output:/output -v ./config.toml:/config.toml    quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=true  --config /config.toml  quay.io/fedora/fedora-bootc:41  --chown 107:107  --rootfs xfs`

output:

```
[...snip...]
Writing manifest to image destination
Traceback (most recent call last):
  File "/osbuild-depsolve-dnf", line 30, in <module>
    from osbuild.solver.dnf import DNF as Solver
  File "/osbuild/solver/dnf.py", line 7, in <module>
    import dnf
ModuleNotFoundError: No module named 'dnf'
2024/11/03 19:13:05 error: cannot build manifest: cannot depsolve: running osbuild-depsolve-dnf failed:
DNF error occurred: InternalError: dnf-json output was empty
```

**Comment by sigulete** [comment]
Same issue with me.
It seems a regression because I was able to build an ISO based on quay.io/fedora/fedora-bootc:41 on October 31st.
Now I can't.

**Comment by mvo5** [comment]
Thanks for the issue report - I had a quick look and indeed, there is no "dnf" python module(s) anymore in the f41 container. The existing code assume this, so we need to rework the strategy here.
