### ISSUE TITLE
Bib failed to build out s390x anaconda-iso using centos-stream9 bootc image

### ISSUE THREAD

**Issue by chunfuwen** [osbuild/bootc-image-builder#705]
```

2024-11-06 03:03:41,853 avocado.utils.process process          L0714 INFO | Command 'sudo podman login -u='11009103|stage' -p='eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJkZTQ3ZmY4NTYxNjM0Y2JiYTk4NTQxNWM3NjA2M2FhMSJ9.LlOJnTv7t-ypiMmeDA6_S6hfyNutNgDVw9hRPrTPQ-b61ISTMOtkV06va3QnzzpJg3N9SP0vCvY_802IvntmmgQ2SBTRe3-EoYkjkDtHntdOI-41KYKFIP9fDFM3r5EMcZ6Sw4cw9mGyZ7ZXCEroC2_E6k-IHjunAxrtxEJ50972Ua5OE3HOqxVTox6v6kPtd_sJ_aVZLNi_91CDsPikQtYcXwoMts9oqp7KjVlKKPktxfVlcyNUZnxxyMm6aIQztpp1MDc_EDP8lBuipd8pflbbcP3bcad2tdIPvOcJhEpDS-BBdfuC9u_ci-R9RMWaAJMqOygz74eb6s9DtT2SqmBWowc7KoYr9KvcaGAXpbSLJ_wB4x7NwMSw56hnvROtsyhdWNMHZMKVzZCLGziJSXg9rugdSaREKKUll1b9fYNJeS2JsTOEP0AkNnUKeLOhCVM5L_9qwSYGHfJy6gFNApl-FH5ZKWPKn5wbuZvl4BOuUxUCFnkqDA5-lcFxIO-qVwVyzbSxW2XxptYVMOut9acxfcpisRHWWtMRFERLeR-B39mAgOXvWkys08IiawnN_t3EmS3z1ibl9HmnWvu6qrJ7b4kbmboD0d53zM-VBYWAGA65Xae_xx4J1DWK8mdGEH25Nf2qYzv2VU7bGW6r23uDnhGZYRep05B92ebXb3k' registry.stage.redhat.io ' finished with 0 after 0.437427050s
2024-11-06 03:03:41,853 avocado.provider.bootc_image_builder.bootc_image_build_utils bootc_image_buil L0121 DEBUG| the whole podman command: sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json    -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json   quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=false  --config /config.json  quay.io/centos-bootc/centos-bootc:stream9
2024-11-06 03:03:41,853 avocado.utils.process process          L0657 INFO | Running 'sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t -v /var/lib/libvirt/images/output:/output -v /var/lib/libvirt/images/config.json:/config.json    -v /var/lib/libvirt/images/auth.json:/run/containers/0/auth.json   quay.io/centos-bootc/bootc-image-builder:latest  --type anaconda-iso --tls-verify=false  --config /config.json  quay.io/centos-bootc/centos-bootc:stream9 '
2024-11-06 03:03:41,946 avocado.utils.process process          L0473 DEBUG| [stderr] time="2024-11-06T03:03:41-05:00" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
2024-11-06 03:03:42,664 avocado.utils.process process          L0473 DEBUG| [stdout] Generating manifest manifest-anaconda-iso.json
2024-11-06 03:03:42,888 avocado.utils.process process          L0473 DEBUG| [stdout] Trying to pull quay.io/centos-bootc/centos-bootc:stream9...
2024-11-06 03:03:45,205 avocado.utils.process process          L0473 DEBUG| [stdout] Getting image source signatures
2024-11-06 03:04:01,929 avocado.utils.process process          L0473 DEBUG| [stdout] Writing manifest to image destination
2024-11-06 03:04:03,934 avocado.utils.process process          L0473 DEBUG| [stdout] panic: unsupported arch: s390x

2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] goroutine 1 [running]:
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/osbuild/images/pkg/manifest.(*AnacondaInstaller).anacondaBootPackageSet(0xc0001bfc00)
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/osbuild/images@v0.95.0/pkg/manifest/anaconda_installer.go:145
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout]  +0x382
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/osbuild/images/pkg/manifest.(*AnacondaInstaller).getBuildPackages(0xc0001bfc00, 0x2)
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/osbuild/images@v0.95.0/pkg/manifest/anaconda_installer.go:152 +0x36
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/osbuild/images/pkg/manifest.(*BuildrootFromPackages).getPackageSetChain(0xc000724120, 0x2)
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/osbuild/images@v0.95.0/pkg/manifest/build.go:86 +0x25a
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/osbuild/images/pkg/manifest.Manifest.GetPackageSetChains({{0xc0006bea00, 0x6, 0x8}, 0x2})
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/osbuild/images@v0.95.0/pkg/manifest/manifest.go:107 +0xa4
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] main.makeManifest(0xc0006be900, 0xc000724000, {0x2a3e1ee, 0x6})
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/build/bib/cmd/bootc-image-builder/main.go:114 +0xc8
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] main.manifestFromCobra(0xc000652908, {0xc00007ecc0, 0x1, 0x6})
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/build/bib/cmd/bootc-image-builder/main.go:309 +0x1266
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] main.cmdBuild(0xc000652908, {0xc00007ecc0, 0x1, 0x6})
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/build/bib/cmd/bootc-image-builder/main.go:420 +0x822
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/spf13/cobra.(*Command).execute(0xc000652908, {0xc00007ec00, 0x6, 0x6})
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xb7a
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/spf13/cobra.(*Command).ExecuteC(0xc000652608)
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x564
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] github.com/spf13/cobra.(*Command).Execute(...)
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] 	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
2024-11-06 03:04:03,935 avocado.utils.process process          L0473 DEBUG| [stdout] main.run()
2024-11-06 03:04:03,936 avocado.utils.process process          L0473 DEBUG| [stdout] 	/build/bib/cmd/bootc-image-builder/main.go:652 +0x4e
2024-11-06 03:04:03,936 avocado.utils.process process          L0473 DEBUG| [stdout] main.main()
2024-11-06 03:04:03,936 avocado.utils.process process          L0473 DEBUG| [stdout] 	/build/bib/cmd/bootc-image-builder/main.go:656 +0x24

...
```

**Comment by chunfuwen** [comment]
This issue can reproduce on stream10, fedora-bootc:41, and almost all bootc images.

**Comment by smitterl** [comment]
Any update on this? I can reproduce this today with quay.io/centos-bootc/bootc-image-builder:latest

```
# podman run --rm -it --privileged    --pull=newer     --security-opt label=type:unconfined_t     -v $(pwd)/config.toml:/config.toml:ro     -v $(pwd)/output:/output     -v /var/lib/containers/storage:/var/lib/containers/storage     quay.io/centos-bootc/bootc-image-builder:latest     --type anaconda-iso --tls-verify=false --local <local-image>
Trying to pull quay.io/centos-bootc/bootc-image-builder:latest...
Getting image source signatures
Copying blob 3a3f0323cc5f done   | 
Copying blob dd894b07b5d0 done   | 
Copying blob 2d6e7f32dafa done   | 
Copying config 5fe98fabfc done   | 
Writing manifest to image destination
[-] Manifest generation step
Message: Generating manifest manifest-anaconda-iso.json
panic: unsupported arch: s390x

goroutine 1 [running]:
github.com/osbuild/images/pkg/manifest.(*AnacondaInstaller).anacondaBootPackageSet(0xc000505c00)
	/root/go/pkg/mod/github.com/osbuild/images@v0.108.0/pkg/manifest/anaconda_installer.go:145 +0x382
github.com/osbuild/images/pkg/manifest.(*AnacondaInstaller).getBuildPackages(0xc000505c00, 0x2)
	/root/go/pkg/mod/github.com/osbuild/images@v0.108.0/pkg/manifest/anaconda_installer.go:152 +0x36
github.com/osbuild/images/pkg/manifest.(*BuildrootFromPackages).getPackageSetChain(0xc000a066c0, 0x2)
	/root/go/pkg/mod/github.com/osbuild/images@v0.108.0/pkg/manifest/build.go:86 +0x25a
github.com/osbuild/images/pkg/manifest.Manifest.GetPackageSetChains({{0xc00061a380, 0x5, 0x8}, 0x2})
	/root/go/pkg/mod/github.com/osbuild/images@v0.108.0/pkg/manifest/manifest.go:107 +0xa4
main.makeManifest(0xc00061a200, 0xc000a065a0, {0x2a899b6, 0x6})
	/build/bib/cmd/bootc-image-builder/main.go:114 +0xc8
main.manifestFromCobra(0xc000a22608, {0xc00069c1e0, 0x1, 0x5}, {0x2e0cc00, 0xc000a09040})
	/build/bib/cmd/bootc-image-builder/main.go:322 +0x129c
main.cmdBuild(0xc000a22608, {0xc00069c1e0, 0x1, 0x5})
	/build/bib/cmd/bootc-image-builder/main.go:447 +0xa02
github.com/spf13/cobra.(*Command).execute(0xc000a22608, {0xc00069c190, 0x5, 0x5})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xb56
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a22308)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x564
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.run()
	/build/bib/cmd/bootc-image-builder/main.go:736 +0x4e
main.main()
	/build/bib/cmd/bootc-image-builder/main.go:740 +0x24
```
